server:
  port: 8999
spring:
  datasource: # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.26.166.99:3306/ciie_2022_db?characterEncoding=utf8&useSSL=false
    username: dfmzadminuser
    password: OPGcitybrain123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# 日志位置
logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logs